import {
  Camera,
  type CameraRef,
  GeoJSONSource,
  Layer,
  type LngLat,
  Map,
  Marker,
  type PressEvent,
  type ViewStateChangeEvent,
} from "@maplibre/maplibre-react-native";
import { useAudioPlayer } from "expo-audio";
import * as Speech from "expo-speech";
import { useKeepAwake } from "expo-keep-awake";
import { router, useLocalSearchParams } from "expo-router";
import { type ReactElement, useCallback, useEffect, useMemo, useRef, useState } from "react";
import {
  Alert,
  BackHandler,
  type NativeSyntheticEvent,
  Pressable,
  Share,
  StyleSheet,
  Text,
  useWindowDimensions,
  View,
} from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import Svg, { Path } from "react-native-svg";

import { ChatSheet } from "../../src/components/ChatSheet";
import { ChatToast } from "../../src/components/ChatToast";
import { ChromeProvider, chromeFor, useChrome } from "../../src/components/ChromeTheme";
import { DestinationSearch } from "../../src/components/DestinationSearch";
import { GroupTripCard } from "../../src/components/GroupTripCard";
import { ManeuverBanner } from "../../src/components/ManeuverBanner";
import { RiderMarker } from "../../src/components/RiderMarker";
import { useRider } from "../../src/components/RiderProvider";
import { RiderSheet } from "../../src/components/RiderSheet";
import { RoutePreview } from "../../src/components/RoutePreview";
import { SosAlarm } from "../../src/components/SosAlarm";
import { TripPanel } from "../../src/components/TripPanel";
import { VoiceBar } from "../../src/components/VoiceBar";
import { useGlide } from "../../src/hooks/useGlide";
import { useLiveLocation } from "../../src/hooks/useLiveLocation";
import { useNavigation } from "../../src/hooks/useNavigation";
import { useRideChannel } from "../../src/hooks/useRideChannel";
import { useRideChat } from "../../src/hooks/useRideChat";
import { useVoiceCall } from "../../src/hooks/useVoiceCall";
import { type ChatMessage, isCoordinator } from "../../src/lib/chat";
import {
  PARTY_HEARTBEAT_MS,
  STALE_AFTER_MS,
} from "../../src/lib/config";
import {
  bearingDegrees,
  boundsOf,
  compassPoint,
  distanceMeters,
  formatSpeed,
} from "../../src/lib/geo";
import { reverseGeocode } from "../../src/lib/geocode";
import {
  pickGroupTrip,
  sameDestination,
  sanitizeTrip,
  tripForPresence,
} from "../../src/lib/groupTrip";
import { initialsOf } from "../../src/lib/identity";
import {
  type MapTheme,
  mapStyleFor,
  OVERLAY_BEFORE_LAYER,
  routeColors,
  themeForHour,
} from "../../src/lib/mapTheme";
import { angleDelta, wrapDegrees } from "../../src/lib/motion";
import { endParty, findParty, type Party, touchParty } from "../../src/lib/party";
import { forgetRide, rememberRide } from "../../src/lib/recentRides";
import { colorForRider } from "../../src/lib/riderColor";
import { normalizeRideCode, rideCodeToLink } from "../../src/lib/rideCode";
import type { Destination, RiderState } from "../../src/lib/types";
import { font, type Palette, radius, space } from "../../src/theme";

/**
 * How the camera behaves as new positions arrive.
 *
 * `preview` is the brief look at the whole route when one arrives. It is a
 * distinct mode rather than reusing `overview` because overview continuously
 * re-fits to the riders, which would drag the camera away from the route and
 * never let go.
 */
type FollowMode = "follow" | "overview" | "preview" | "free";

const FOLLOW_ZOOM = 16;
/** Closer and tilted while navigating, so the next turn fills the screen. */
const NAV_ZOOM = 17.2;
const NAV_PITCH = 55;

const OVERVIEW_PADDING = { top: 180, right: 70, bottom: 280, left: 70 };

/** How long the camera stays where the rider left it before following again. */
const RESUME_FOLLOW_MS = 10000;

/**
 * How long the marker glides to each new position, and how long the camera
 * takes to follow it. They must match — and both move linearly — or the
 * marker and the map drift apart and the rider sees it wobble.
 */
const GLIDE_MS = 1000;

/** Other riders update every few seconds, so they glide for longer. */
const OTHERS_GLIDE_MS = 1500;

/**
 * Within this distance of the route, the rider is drawn on the line itself.
 *
 * Kept tight: a side street runs 20–30 m from the main road in town, and
 * snapping from there drew the rider on a road they were not on.
 */
const SNAP_M = 15;

const NO_PADDING = { top: 0, right: 0, bottom: 0, left: 0 };

/** "SOS" in Morse, generated by `scripts/make-sos-sound.js`. */
const SOS_SOUND = require("../../assets/sounds/sos.wav");
/** Loud enough to notice over traffic noise in a pocket, not a siren. */
const SOS_VOLUME = 0.6;
/** The tone lasts about 2.6 s; this leaves a calm gap between repeats. */
const SOS_REPEAT_MS = 8000;

export default function RideScreen() {
  // Starts in day or night by the clock; the rider can flip it by hand.
  const [theme, setTheme] = useState<MapTheme>(() => themeForHour(new Date().getHours()));
  const palette = chromeFor(theme);

  return (
    <ChromeProvider palette={palette}>
      <RideScreenInner theme={theme} setTheme={setTheme} />
    </ChromeProvider>
  );
}

function RideScreenInner({
  theme,
  setTheme,
}: {
  theme: MapTheme;
  setTheme: (next: MapTheme) => void;
}) {
  useKeepAwake();

  const params = useLocalSearchParams<{ code: string }>();
  const code = normalizeRideCode(params.code ?? "");
  const { rider, ready } = useRider();
  const insets = useSafeAreaInsets();
  const cameraRef = useRef<CameraRef>(null);
  const resumeTimer = useRef<ReturnType<typeof setTimeout> | null>(null);

  const c = useChrome();
  const styles = useMemo(() => makeStyles(c), [c]);
  const route = routeColors[theme];

  const [party, setParty] = useState<Party | null>(null);
  const [lookupError, setLookupError] = useState<string | null>(null);
  const [followMode, setFollowMode] = useState<FollowMode>("follow");
  const [sheetExpanded, setSheetExpanded] = useState(false);
  const [searchOpen, setSearchOpen] = useState(false);
  /** Whether the open search will append a stop rather than start a new plan. */
  const [addingStop, setAddingStop] = useState(false);
  const [now, setNow] = useState(() => Date.now());
  const [sosActive, setSosActive] = useState(false);
  // Riders whose alarm this device has silenced; their marker stays red.
  const [silenced, setSilenced] = useState<string[]>([]);
  /** Set once the host has ended the ride and the party is confirmed gone. */
  const [ended, setEnded] = useState(false);
  const [chatOpen, setChatOpen] = useState(false);
  const [toast, setToast] = useState<ChatMessage | null>(null);
  /** The group trip this rider put off; it shrinks to a bar, and a new trip asks again. */
  const [laterTrip, setLaterTrip] = useState<string | null>(null);
  /**
   * The bearing the map is turned to, as last commanded or dragged.
   *
   * Markers are views over the map and do not turn with it, so every
   * direction drawn on one has this taken off first.
   */
  const [mapBearing, setMapBearing] = useState(0);
  const { height: screenHeight } = useWindowDimensions();
  /** Whose destination this rider last accepted, to word a change of plan. */
  const [followedLeader, setFollowedLeader] = useState<string | null>(null);

  // Both of these mirror navigation state that is only known further down the
  // hook order: the GPS watcher and the presence payload have to be told
  // before `useNavigation` has run and produced the status that justifies it.
  const [highRate, setHighRate] = useState(false);
  const [riding, setRiding] = useState(false);

  const isHost = Boolean(party && rider && party.hostId === rider.id);

  const location = useLiveLocation(ready, highRate);
  const nav = useNavigation(location.fix);

  /** Where this rider is going, shared so the rest of the party can follow. */
  const trip = useMemo(
    () => (riding && nav.stops.length > 0 ? tripForPresence(nav.stops) : null),
    [riding, nav.stops],
  );

  const profile = useMemo(
    () => ({
      id: rider?.id ?? "",
      name: rider?.name ?? "Rider",
      isHost,
      sos: sosActive,
      navigating: riding,
      trip,
    }),
    [rider?.id, rider?.name, isHost, sosActive, riding, trip],
  );

  const connected = ready && Boolean(rider?.id) && !ended;
  const channel = useRideChannel(code, profile, connected);
  const { publish, republish, riders, endedSignal, announceEnd } = channel;

  const riderIds = useMemo(() => riders.map((r) => r.id), [riders]);
  const chat = useRideChat(
    code,
    { id: rider?.id ?? "", name: rider?.name || "Rider" },
    riderIds,
    connected,
    chatOpen,
  );
  const voice = useVoiceCall(code, { id: rider?.id ?? "", name: rider?.name || "Rider" }, connected);
  const inCall = voice.state === "live";
  const othersInCall = voice.members.filter((m) => m.id !== rider?.id).length;

  const navigating =
    nav.status === "navigating" ||
    nav.status === "rerouting" ||
    nav.status === "arrived";

  /** Routes are on screen and the rider is choosing; the ride has not begun. */
  const choosing = nav.status === "preview";

  useEffect(() => {
    setHighRate(nav.status === "navigating" || nav.status === "rerouting");
    setRiding(navigating);
  }, [nav.status, navigating]);

  // Tell the party as soon as the journey starts, ends or changes destination,
  // so everyone's marker and suggestion update without waiting for a GPS tick.
  useEffect(() => {
    republish();
  }, [riding, trip, republish]);

  /**
   * Where this rider is drawn.
   *
   * While navigating and demonstrably on the route, the snapped point is used
   * instead of the raw fix. GPS wanders a few metres either side of the
   * carriageway; snapping keeps the marker on the road the rider is actually
   * riding, which is most of what makes a map feel accurate.
   */
  const courseAgrees =
    location.course == null ||
    nav.routeBearing == null ||
    Math.abs(angleDelta(location.course, nav.routeBearing)) < 60;
  const onRoute = Boolean(
    navigating && nav.progress && nav.progress.deviationM < SNAP_M && courseAgrees,
  );

  const displayPosition = useMemo(() => {
    if (onRoute && nav.progress) return nav.progress.snapped;
    return location.fix?.lngLat ?? null;
  }, [onRoute, nav.progress, location.fix]);

  /**
   * Which way the driving view faces.
   *
   * On the route, the road's own direction: it cannot jitter, and it turns
   * the map smoothly through a bend. Off it, the GPS course. Never the
   * compass, which swings next to an engine and used to spin the whole map at
   * every red light. Held at its last value while nothing better is known.
   */
  const navBearingRef = useRef<number | null>(null);
  const liveNavBearing = onRoute ? nav.routeBearing : location.course;
  if (liveNavBearing != null) navBearingRef.current = liveNavBearing;
  if (!navigating) navBearingRef.current = null;
  const navBearing = navigating ? navBearingRef.current : null;

  /** Which way this rider's own marker points, in degrees from north. */
  const selfHeading = navigating ? (navBearing ?? location.heading) : location.heading;

  /** A north-referenced heading turned into a rotation on screen. */
  const onScreen = useCallback(
    (heading: number | null) => (heading == null ? null : wrapDegrees(heading - mapBearing)),
    [mapBearing],
  );

  /** Looking ahead: the rider sits low on screen with the road above them. */
  const navPadding = useMemo(
    () => ({
      top: Math.round(screenHeight * 0.42),
      right: 0,
      bottom: Math.round(screenHeight * 0.08),
      left: 0,
    }),
    [screenHeight],
  );

  // Confirm the party exists and pick up its name and host.
  useEffect(() => {
    if (!code) return;
    let cancelled = false;

    void findParty(code).then((result) => {
      if (cancelled) return;
      if (result.status === "ok") {
        setParty(result.party);
        // So a dropped connection or a stray back swipe is one tap from
        // being undone on the home screen.
        void rememberRide(code, result.party.hostName);
        return;
      }
      if (result.status === "not_found") void forgetRide(code);
      setLookupError(
        result.status === "error"
          ? result.message
          : "This ride is no longer available.",
      );
    });

    return () => {
      cancelled = true;
    };
  }, [code]);

  /**
   * Keeps the party open while anyone is in it.
   *
   * Every rider refreshes it once on arrival — a newcomer should never find a
   * party that is about to lapse — and after that only the coordinator does,
   * so a party costs one tiny write every few minutes however big it is. When
   * everyone has gone the beats stop and the server closes the party itself.
   */
  const coordinatorRef = useRef(false);
  coordinatorRef.current = Boolean(rider?.id) && isCoordinator(rider?.id ?? "", riderIds);

  useEffect(() => {
    if (!party || ended) return;
    void touchParty(code);
    const timer = setInterval(() => {
      if (coordinatorRef.current) void touchParty(code);
    }, PARTY_HEARTBEAT_MS);
    return () => clearInterval(timer);
  }, [party, ended, code]);

  /**
   * The host has announced the end of the ride.
   *
   * Anyone in the channel could send that event, so it is only believed once
   * the party is confirmed deleted — which only the host's secret can do.
   */
  const stopNavigation = nav.stop;
  useEffect(() => {
    if (!endedSignal || isHost) return;
    let cancelled = false;

    void findParty(code).then((result) => {
      if (cancelled || result.status !== "not_found") return;
      void forgetRide(code);
      stopNavigation();
      setSosActive(false);
      setEnded(true);
    });

    return () => {
      cancelled = true;
    };
  }, [endedSignal, isHost, code, stopNavigation]);

  // Slow tick so the "live / 20s ago" labels stay truthful between updates.
  useEffect(() => {
    const timer = setInterval(() => setNow(Date.now()), 5000);
    return () => clearInterval(timer);
  }, []);

  useEffect(() => {
    if (location.fix) publish(location.fix);
  }, [location.fix, publish]);

  const fitEveryone = useCallback(
    (duration: number) => {
      const points = riders.map((r) => [r.lng, r.lat] as [number, number]);
      for (const stop of nav.stops) points.push(stop.lngLat);
      const bounds = boundsOf(points);
      if (!bounds) return false;
      cameraRef.current?.fitBounds(bounds, {
        padding: OVERVIEW_PADDING,
        duration,
        pitch: 0,
      });
      return true;
    },
    [riders, nav.stops],
  );

  /** Moves the camera onto this rider, in the driving or the parked view. */
  const mapBearingRef = useRef(mapBearing);
  mapBearingRef.current = mapBearing;
  const follow = useCallback(
    (duration: number, easing: "linear" | "ease") => {
      if (!displayPosition) return;
      // The current bearing is only a fallback while no direction is known.
      const bearing = navigating ? (navBearing ?? mapBearingRef.current) : 0;
      setMapBearing(bearing);
      cameraRef.current?.easeTo({
        center: displayPosition,
        zoom: navigating ? NAV_ZOOM : FOLLOW_ZOOM,
        pitch: navigating ? NAV_PITCH : 0,
        bearing,
        padding: navigating ? navPadding : NO_PADDING,
        duration,
        easing,
      });
    },
    [displayPosition, navigating, navBearing, navPadding],
  );

  const recenter = useCallback(() => {
    setFollowMode("follow");
    follow(600, "ease");
  }, [follow]);

  const showEveryone = useCallback(() => {
    if (fitEveryone(700)) setFollowMode("overview");
  }, [fitEveryone]);

  const focusRider = useCallback((target: RiderState) => {
    setFollowMode("free");
    cameraRef.current?.flyTo({
      center: [target.lng, target.lat],
      zoom: FOLLOW_ZOOM,
      padding: NO_PADDING,
      duration: 700,
    });
  }, []);

  /**
   * Follow-mode camera.
   *
   * Navigating swings the map to course-up and tilts it, which is what makes
   * the 3D buildings in the basemap readable and tells the rider which way
   * they are pointing without reading anything. Otherwise it stays north-up
   * and flat, which is easier for comparing where the group is.
   */
  useEffect(() => {
    if (followMode !== "follow") return;
    // Linear and exactly as long as the marker's glide, so the two arrive
    // together instead of the marker hopping ahead of the map.
    follow(GLIDE_MS, "linear");
  }, [followMode, follow]);

  useEffect(() => {
    if (followMode !== "overview") return;
    fitEveryone(900);
  }, [followMode, fitEveryone]);

  /**
   * While choosing, frame whichever route is highlighted so the rider can see
   * what they are picking. The camera stays put — nothing is under way yet.
   */
  useEffect(() => {
    if (!choosing || !nav.route) return;

    setFollowMode("preview");
    cameraRef.current?.fitBounds(nav.route.bounds, {
      padding: OVERVIEW_PADDING,
      duration: 700,
      pitch: 0,
    });
  }, [choosing, nav.route]);

  /**
   * Pressing Start dives into the driving view.
   *
   * The hand-back to follow mode is the important half: leaving the camera
   * framed on the whole route would mean the rider never gets the tilted,
   * course-up view they actually ride with.
   */
  useEffect(() => {
    if (nav.status !== "navigating" || nav.rerouteCount > 0) return;
    setFollowMode("follow");
  }, [nav.status, nav.rerouteCount]);

  /**
   * A drag or pinch releases the camera. Programmatic moves raise this same
   * event, so `userInteraction` is what separates the two.
   *
   * Each interaction restarts an idle timer that hands the camera back: a
   * rider who pans ahead should not have to remember to press recentre before
   * the next turn.
   */
  const onRegionChange = (event: NativeSyntheticEvent<ViewStateChangeEvent>) => {
    // Whatever turned the map — a two-finger twist, or fitting a route —
    // markers have to turn with it.
    const turned = event.nativeEvent.bearing;
    if (Math.abs(angleDelta(mapBearing, turned)) > 1) setMapBearing(turned);

    if (!event.nativeEvent.userInteraction) return;

    setFollowMode("free");
    if (resumeTimer.current) clearTimeout(resumeTimer.current);
    resumeTimer.current = setTimeout(() => setFollowMode("follow"), RESUME_FOLLOW_MS);
  };

  useEffect(() => {
    if (followMode === "free") return;
    if (resumeTimer.current) {
      clearTimeout(resumeTimer.current);
      resumeTimer.current = null;
    }
  }, [followMode]);

  useEffect(
    () => () => {
      if (resumeTimer.current) clearTimeout(resumeTimer.current);
    },
    [],
  );

  /** Press and hold anywhere to ride there. */
  const onLongPress = async (event: NativeSyntheticEvent<PressEvent>) => {
    const { lngLat } = event.nativeEvent;
    const place = await reverseGeocode(lngLat);
    const dropped: Destination = { lngLat, label: place?.name ?? "Dropped pin" };
    if (addingStop) nav.addStop(dropped);
    else nav.plan([dropped]);
    setAddingStop(false);
  };

  const pickDestination = (destination: Destination) => {
    setSearchOpen(false);
    // The same picker serves both jobs; which one depends on how it was opened.
    if (addingStop) nav.addStop(destination);
    else nav.plan([destination]);
    setAddingStop(false);
  };

  const cycleStyle = () => {
    setTheme(theme === "day" ? "night" : "day");
  };

  const leave = () => {
    if (!isHost) {
      Alert.alert(
        "Leave this ride?",
        "The group carries on without you. While the ride is still going you can get back in from the home screen with one tap.",
        [
          { text: "Stay", style: "cancel" },
          { text: "Leave", style: "destructive", onPress: () => router.replace("/") },
        ],
      );
      return;
    }

    Alert.alert(
      "End this ride?",
      "Ending the party closes it for everyone. Leaving on your own keeps it open for the rest of the group.",
      [
        { text: "Cancel", style: "cancel" },
        { text: "Just leave", onPress: () => router.replace("/") },
        {
          text: "End ride",
          style: "destructive",
          onPress: async () => {
            // Awaited before leaving: navigating away closes the channel, and
            // the announcement has to be out of the door first.
            const closed = await endParty(code);
            if (closed) {
              await announceEnd().catch(() => undefined);
              void forgetRide(code);
            }
            router.replace("/");
            if (!closed) {
              Alert.alert(
                "Could not end the ride",
                "This device no longer holds the host key for this party, so it stays open. You have been taken out of it.",
              );
            }
          },
        },
      ],
    );
  };

  // Android's back gesture used to drop the rider out of the ride without a
  // word — easy to do by accident with gloves on. It now asks first.
  const leaveRef = useRef(leave);
  leaveRef.current = leave;
  useEffect(() => {
    const sub = BackHandler.addEventListener("hardwareBackPress", () => {
      if (searchOpen || chatOpen) return false; // their own modals close first
      leaveRef.current();
      return true;
    });
    return () => sub.remove();
  }, [searchOpen, chatOpen]);

  // Raising or clearing an SOS must reach the party now, not on the next GPS
  // tick, so the state is pushed the moment it changes.
  useEffect(() => {
    republish();
  }, [sosActive, republish]);

  /** Riders other than this one who currently have an SOS raised. */
  const distressed = useMemo(
    () => riders.filter((r) => r.sos && r.id !== rider?.id),
    [riders, rider?.id],
  );

  /** The one we should be shouting about: raised, and not silenced here. */
  const alert = distressed.find((r) => !silenced.includes(r.id)) ?? null;

  // Drop anyone from the silenced list once their SOS clears, so a second
  // emergency from the same rider alarms again.
  useEffect(() => {
    setSilenced((current) =>
      current.filter((id) => distressed.some((r) => r.id === id)),
    );
  }, [distressed]);

  /**
   * The alarm itself: "SOS" in Morse, as a soft tone, every few seconds.
   *
   * Deliberately restrained — no vibration, no voice, no siren. It has to be
   * noticed, but it keeps going until someone taps Silence, and a harsh sound
   * on repeat makes people reach for the mute rather than the map. The banner
   * at the top already names who is in trouble and how far away they are.
   */
  const sosPlayer = useAudioPlayer(SOS_SOUND);
  const alertId = alert?.id ?? null;
  useEffect(() => {
    if (!alertId) return;

    sosPlayer.volume = SOS_VOLUME;
    const ring = () => {
      sosPlayer.seekTo(0);
      sosPlayer.play();
    };
    ring();
    const timer = setInterval(ring, SOS_REPEAT_MS);

    return () => {
      clearInterval(timer);
      sosPlayer.pause();
    };
  }, [alertId, sosPlayer]);

  /**
   * One tap raises it, with no confirmation: a rider who needs it may not
   * manage a second tap. A mistaken SOS is cancelled with one more press,
   * which clears it for everyone at once.
   */
  const raiseSos = () => {
    if (sosActive) {
      setSosActive(false);
      return;
    }
    setSosActive(true);
  };

  // --- group destination --------------------------------------------------

  const groupTrip = useMemo(
    () => (rider?.id ? pickGroupTrip(riders, rider.id) : null),
    [riders, rider?.id],
  );

  /** This rider is already heading to (or planning) the group's destination. */
  const onGroupTrip = Boolean(
    groupTrip && nav.stops.length > 0 && sameDestination(nav.stops, groupTrip.stops),
  );

  // Hidden while a route is being built or chosen: the rider is mid-decision,
  // and the panel below already has their full attention.
  const suggestion =
    groupTrip && !onGroupTrip && nav.status !== "routing" && !choosing ? groupTrip : null;

  /** Put off with "Later": shown as a slim bar rather than the full card. */
  const suggestionCollapsed = Boolean(suggestion && suggestion.key === laterTrip);

  const suggestionChanged = Boolean(
    suggestion && followedLeader === suggestion.leader.id && nav.stops.length > 0,
  );

  // A nudge when a new suggestion appears. Spoken only mid-ride, where the
  // rider will not be looking; parked, the card is enough.
  const suggestionKey = suggestion?.key ?? null;
  const voiceOn = nav.voiceEnabled;
  useEffect(() => {
    if (!suggestion || suggestionCollapsed) return;
    if (navigating && voiceOn && !alertId) {
      const place = suggestion.stops[suggestion.stops.length - 1].label;
      Speech.speak(
        suggestionChanged
          ? `${suggestion.leader.name || "The leader"} changed destination to ${place}.`
          : `${suggestion.leader.name || "A rider"} is heading to ${place}.`,
        { language: "en-US" },
      );
    }
    // Only a new suggestion should announce itself, not every position update.
  }, [suggestionKey]);

  const acceptGroupTrip = () => {
    if (!groupTrip) return;
    setFollowedLeader(groupTrip.leader.id);
    // A fresh plan from where this rider is, through the leader's stops: same
    // place, this rider's own road there.
    nav.plan(groupTrip.stops);
  };

  /** Rides to wherever one particular rider is going, picked from the list. */
  const joinTripOf = (other: RiderState) => {
    const stops = sanitizeTrip(other.trip);
    if (!other.navigating || !stops) return;
    setFollowedLeader(other.id);
    setSheetExpanded(false);
    nav.plan(stops);
  };

  // --- chat -----------------------------------------------------------------

  const { latest: latestMessage, markRead } = chat;

  useEffect(() => {
    if (chatOpen) {
      markRead();
      setToast(null);
    }
  }, [chatOpen, markRead, chat.unread]);

  // Preview each new message over the map, and read it out mid-ride.
  useEffect(() => {
    if (!latestMessage || chatOpen) return;
    setToast(latestMessage);
    if (navigating && voiceOn && !alertId) {
      Speech.speak(`${latestMessage.name} says: ${latestMessage.text}`, { language: "en-US" });
    }
    const timer = setTimeout(() => setToast(null), 6000);
    return () => clearTimeout(timer);
    // Keyed on the message, so a toast is not replayed when anything else moves.
  }, [latestMessage?.id]);

  const shareInvite = async () => {
    await Share.share({
      message: `Join my ride on Cruzo.\n\nCode: ${code}\n${rideCodeToLink(code)}`,
    });
  };

  /**
   * The route split at the rider's current position, so the road already
   * covered can be drawn dimmed and the road ahead bright.
   */
  const routeLines = useMemo(() => {
    if (!nav.route) return null;
    const { shape } = nav.route;
    const progress = nav.progress;

    if (!progress) return { travelled: null, ahead: shape };

    const cut = Math.min(progress.segmentIndex + 1, shape.length);
    return {
      travelled: [...shape.slice(0, cut), progress.snapped],
      ahead: [progress.snapped, ...shape.slice(cut)],
    };
  }, [nav.route, nav.progress]);

  const riderOptions = useMemo(
    () =>
      riders
        .filter((r) => r.id !== rider?.id)
        .map((r) => ({
          id: r.id,
          name: r.name || "Rider",
          lngLat: [r.lng, r.lat] as [number, number],
          color: colorForRider(r.id),
        })),
    [riders, rider?.id],
  );


  if (lookupError || ended) {
    return (
      <View style={[styles.errorRoot, { paddingTop: insets.top + space.xxl }]}>
        <Text style={styles.errorTitle}>{ended ? "Ride ended" : "Ride unavailable"}</Text>
        <Text style={styles.errorBody}>
          {ended
            ? `${party?.hostName ?? "The host"} has ended the ride. The party and its chat are closed.`
            : lookupError}
        </Text>
        <Pressable
          onPress={() => router.replace("/")}
          accessibilityRole="button"
          style={styles.errorButton}
        >
          <Text style={styles.errorButtonText}>Back to start</Text>
        </Pressable>
      </View>
    );
  }

  const statusLabel =
    channel.status === "connected"
      ? location.fix
        ? "Live"
        : "Waiting for GPS"
      : channel.status === "connecting"
        ? "Connecting"
        : channel.status === "reconnecting"
          ? "Reconnecting"
          : channel.status === "error"
            ? "Offline"
            : "Idle";

  const statusColor =
    channel.status === "connected" && location.fix
      ? c.success
      : channel.status === "error"
        ? c.danger
        : c.warning;

  const upcoming =
    nav.route && nav.progress
      ? (nav.route.maneuvers[nav.progress.upcomingIndex] ?? null)
      : null;
  const following =
    nav.route && nav.progress
      ? (nav.route.maneuvers[nav.progress.upcomingIndex + 1] ?? null)
      : null;

  return (
    <View style={styles.root}>
      <Map
        style={StyleSheet.absoluteFill}
        mapStyle={mapStyleFor[theme]}
        onRegionDidChange={onRegionChange}
        onLongPress={onLongPress}
        logo={false}
        attribution
        attributionPosition={{ bottom: 6, left: 6 }}
        compass
        // Kept on the left: the right edge is a column of controls, and the
        // compass used to land on top of the follow button.
        compassPosition={{ top: insets.top + (navigating ? 168 : 112), left: 12 }}
        compassHiddenFacingNorth
      >
        <Camera
          ref={cameraRef}
          initialViewState={{ center: [90.4125, 23.8103], zoom: 11 }}
        />

        {/* Unselected alternatives, drawn underneath and muted so the chosen
            one stays obvious. Only shown while choosing. */}
        {choosing && nav.routes.length > 1
          ? nav.routes.map((r, i) =>
              i === nav.selectedIndex || r.shape.length < 2 ? null : (
                <GeoJSONSource
                  key={`alt-${i}`}
                  id={`cruzo-route-alt-${i}`}
                  data={{
                    type: "Feature",
                    properties: {},
                    geometry: { type: "LineString", coordinates: r.shape },
                  }}
                >
                  <Layer
                    id={`cruzo-route-alt-casing-${i}`}
                    type="line"
                    beforeId={OVERLAY_BEFORE_LAYER}
                    layout={{ "line-cap": "round", "line-join": "round" }}
                    paint={{ "line-color": route.altCasing, "line-width": 10 }}
                  />
                  <Layer
                    id={`cruzo-route-alt-line-${i}`}
                    type="line"
                    beforeId={OVERLAY_BEFORE_LAYER}
                    layout={{ "line-cap": "round", "line-join": "round" }}
                    paint={{ "line-color": route.alt, "line-width": 7 }}
                  />
                </GeoJSONSource>
              ),
            )
          : null}

        {routeLines ? (
          <>
            {routeLines.travelled && routeLines.travelled.length > 1 ? (
              <GeoJSONSource
                id="cruzo-route-travelled"
                data={{
                  type: "Feature",
                  properties: {},
                  geometry: { type: "LineString", coordinates: routeLines.travelled },
                }}
              >
                <Layer
                  id="cruzo-route-travelled-line"
                  type="line"
                  beforeId={OVERLAY_BEFORE_LAYER}
                  layout={{ "line-cap": "round", "line-join": "round" }}
                  paint={{
                    "line-color": route.travelled,
                    "line-width": 8,
                    "line-opacity": 0.7,
                  }}
                />
              </GeoJSONSource>
            ) : null}

            {routeLines.ahead.length > 1 ? (
              <GeoJSONSource
                id="cruzo-route-ahead"
                data={{
                  type: "Feature",
                  properties: {},
                  geometry: { type: "LineString", coordinates: routeLines.ahead },
                }}
              >
                {/* A darker blue border under a bright blue line, as Google
                    draws it: it reads on white streets and yellow highways
                    alike, and widens with zoom so it is never a hairline. */}
                <Layer
                  id="cruzo-route-casing"
                  type="line"
                  beforeId={OVERLAY_BEFORE_LAYER}
                  layout={{ "line-cap": "round", "line-join": "round" }}
                  paint={{
                    "line-color": route.casing,
                    "line-width": ["interpolate", ["linear"], ["zoom"], 10, 7, 15, 12, 18, 20],
                  }}
                />
                <Layer
                  id="cruzo-route-line"
                  type="line"
                  beforeId={OVERLAY_BEFORE_LAYER}
                  layout={{ "line-cap": "round", "line-join": "round" }}
                  paint={{
                    "line-color": route.line,
                    "line-width": ["interpolate", ["linear"], ["zoom"], 10, 4.5, 15, 8, 18, 14],
                  }}
                />
              </GeoJSONSource>
            ) : null}
          </>
        ) : null}

        {/* Every stop on the trip. Intermediate ones are numbered so the order
            is readable straight off the map. */}
        {nav.stops.map((s, i) => {
          const last = i === nav.stops.length - 1;
          return (
            <Marker key={`stop-${i}-${s.label}`} lngLat={s.lngLat} anchor="bottom">
              <View style={styles.destPin} pointerEvents="none">
                <View style={[styles.destPinHead, !last && styles.destPinHeadVia]}>
                  <Text style={[styles.destPinGlyph, !last && styles.destPinGlyphVia]}>
                    {last ? "●" : String(i + 1)}
                  </Text>
                </View>
                <View style={styles.destPinStem} />
              </View>
            </Marker>
          );
        })}

        {/* Where the group is heading, when this rider is not going there yet:
            a flag in the leader's colour, so "where is everyone going?" is
            answered by the map itself. */}
        {groupTrip && !onGroupTrip ? (
          <Marker
            key={`group-${groupTrip.key}`}
            lngLat={groupTrip.stops[groupTrip.stops.length - 1].lngLat}
            anchor="bottom"
          >
            <View style={styles.destPin} pointerEvents="none">
              <Text style={styles.groupPinLabel} numberOfLines={1}>
                {groupTrip.stops[groupTrip.stops.length - 1].label}
              </Text>
              <View
                style={[
                  styles.destPinHead,
                  styles.groupPinHead,
                  { borderColor: colorForRider(groupTrip.leader.id) },
                ]}
              >
                <Text
                  style={[styles.groupPinGlyph, { color: colorForRider(groupTrip.leader.id) }]}
                >
                  ⚑
                </Text>
              </View>
              <View style={styles.destPinStem} />
            </View>
          </Marker>
        ) : null}

        {/* Everyone else first, so your own marker is drawn on top. */}
        {riders.map((entry) =>
          entry.id === rider?.id ? null : (
            <GlidingMarker key={entry.id} at={[entry.lng, entry.lat]} glideMs={OTHERS_GLIDE_MS}>
              <RiderMarker
                initials={initialsOf(entry.name)}
                name={entry.name || "Rider"}
                color={colorForRider(entry.id)}
                rotation={onScreen(entry.heading)}
                isSelf={false}
                isHost={entry.isHost}
                isStale={now - entry.updatedAt > STALE_AFTER_MS}
                isSos={entry.sos}
                isNavigating={entry.navigating}
              />
            </GlidingMarker>
          ),
        )}

        {/* Own marker, from the snapped position and this phone's own sensors
            rather than the copy that went round the party. */}
        {displayPosition ? (
          <GlidingMarker key="self" at={displayPosition} glideMs={GLIDE_MS}>
            <RiderMarker
              initials={initialsOf(rider?.name || "Me")}
              name={rider?.name || "You"}
              color={colorForRider(rider?.id ?? "me")}
              rotation={onScreen(selfHeading)}
              isSelf
              isHost={isHost}
              isStale={false}
              isSos={sosActive}
              isNavigating={navigating}
            />
          </GlidingMarker>
        ) : null}
      </Map>

      <View style={[styles.header, { paddingTop: insets.top + space.sm }]}>
        {alert ? (
          <SosAlarm
            name={alert.name || "A rider"}
            distanceM={
              displayPosition
                ? distanceMeters(displayPosition, [alert.lng, alert.lat])
                : null
            }
            bearing={
              displayPosition
                ? compassPoint(bearingDegrees(displayPosition, [alert.lng, alert.lat]))
                : null
            }
            onShow={() => {
              setFollowMode("free");
              cameraRef.current?.flyTo({
                center: [alert.lng, alert.lat],
                zoom: FOLLOW_ZOOM,
                duration: 700,
              });
            }}
            onDismiss={() => setSilenced((current) => [...current, alert.id])}
          />
        ) : navigating ? (
          <ManeuverBanner
            maneuver={upcoming}
            distanceM={nav.progress?.distanceToManeuverM ?? 0}
            thenInstruction={following?.instruction ?? null}
            rerouting={nav.status === "rerouting"}
            arrived={nav.status === "arrived"}
          />
        ) : (
          <View style={styles.headerCard}>
            <View style={styles.headerMain}>
              <Text style={styles.rideName} numberOfLines={1}>
                {party?.name ?? "Group ride"}
              </Text>
              <View style={styles.statusLine}>
                <View style={[styles.statusDot, { backgroundColor: statusColor }]} />
                <Text style={styles.statusText}>{statusLabel}</Text>
                {/* The code is the only way anyone joins, so it doubles as the
                    share button rather than hiding that on another screen. */}
                <Pressable
                  onPress={() => void shareInvite()}
                  accessibilityRole="button"
                  accessibilityLabel={`Ride code ${code.split("").join(" ")}. Tap to share.`}
                  hitSlop={8}
                >
                  <Text style={styles.codeChip}>{code} ↗</Text>
                </Pressable>
              </View>
            </View>

            <Pressable
              onPress={leave}
              accessibilityRole="button"
              accessibilityLabel={isHost ? "End or leave this ride" : "Leave this ride"}
              style={({ pressed }) => [styles.leave, pressed && styles.leavePressed]}
            >
              <Text style={styles.leaveText}>{isHost ? "End" : "Leave"}</Text>
            </Pressable>
          </View>
        )}
      </View>

      <View style={[styles.controls, { top: insets.top + (navigating ? 168 : 112) }]}>
        <ControlButton
          label="⤢"
          active={followMode === "overview"}
          onPress={showEveryone}
          accessibilityLabel="Fit every rider on screen"
          palette={c}
        />
        <ControlButton
          label={theme === "day" ? "☀" : "☾"}
          onPress={cycleStyle}
          accessibilityLabel={`${theme === "day" ? "Day" : "Night"} map. Tap to switch.`}
          palette={c}
        />
        {/* Out of a call this joins one; in a call it is the quick mute, which
            is what a rider reaches for mid-ride far more than hanging up. */}
        <ControlButton
          label={inCall ? (voice.muted ? "Muted" : "Mute") : "Voice"}
          small
          active={inCall && !voice.muted}
          badge={inCall ? 0 : othersInCall}
          onPress={() => (inCall ? voice.toggleMute() : void voice.join())}
          accessibilityLabel={
            inCall
              ? voice.muted
                ? "Unmute your microphone"
                : "Mute your microphone"
              : othersInCall > 0
                ? `Join the voice call, ${othersInCall} talking`
                : "Start a voice call"
          }
          palette={c}
        />
        <ControlButton
          label="Chat"
          small
          active={chatOpen}
          badge={chat.unread}
          onPress={() => setChatOpen(true)}
          accessibilityLabel={
            chat.unread > 0
              ? `Open ride chat, ${chat.unread} unread`
              : "Open ride chat"
          }
          palette={c}
        />

        {/* Kept with the other controls so it is always in the same place,
            rather than appearing only in some states. */}
        <Pressable
          onPress={raiseSos}
          accessibilityRole="button"
          accessibilityLabel={
            sosActive ? "Cancel your SOS" : "Send an SOS to the party"
          }
          style={({ pressed }) => [
            styles.control,
            styles.sosButton,
            sosActive && styles.sosButtonActive,
            pressed && styles.controlPressed,
          ]}
        >
          <Text style={[styles.sosButtonText, sosActive && styles.sosButtonTextActive]}>
            {sosActive ? "✕" : "SOS"}
          </Text>
        </Pressable>
      </View>

      {toast && !chatOpen ? (
        <ChatToast
          message={toast}
          color={colorForRider(toast.from)}
          top={insets.top + (navigating ? 168 : 112)}
          onOpen={() => setChatOpen(true)}
        />
      ) : null}

      {nav.status === "routing" ? (
        <Banner text="Building your route…" bottomOffset={insets.bottom} palette={c} />
      ) : nav.status === "error" && nav.error ? (
        <Banner
          text={nav.error}
          actionLabel="Retry"
          onAction={nav.recalculate}
          bottomOffset={insets.bottom}
          palette={c}
          warn
        />
      ) : location.permission === "denied" ? (
        <Banner
          text="Location permission is off, so other riders cannot see you."
          actionLabel="Retry"
          onAction={location.retry}
          bottomOffset={insets.bottom}
          palette={c}
          warn
        />
      ) : location.servicesDisabled ? (
        <Banner
          text="Turn on location services to share your position."
          actionLabel="Retry"
          onAction={location.retry}
          bottomOffset={insets.bottom}
          palette={c}
          warn
        />
      ) : null}

      {navigating && location.fix ? (
        <View style={[styles.speedPill, { bottom: insets.bottom + 188 }]} pointerEvents="none">
          <Text style={styles.speedValue}>{formatSpeed(location.fix.speed)}</Text>
          <Text style={styles.speedUnit}>km/h</Text>
        </View>
      ) : null}

      <View style={[styles.bottom, { paddingBottom: insets.bottom }]}>
        {/* Shown the moment the map is not following this rider — after a
            drag, looking at the whole group, or checking on another rider —
            and one tap from being back, as in Google Maps. Sits on the right
            so it never covers the speed readout on the left. */}
        {followMode !== "follow" && displayPosition ? (
          <Pressable
            onPress={recenter}
            accessibilityRole="button"
            accessibilityLabel="Re-centre the map on your position"
            hitSlop={8}
            style={({ pressed }) => [styles.recenter, pressed && styles.pressed]}
          >
            <Svg width={18} height={18} viewBox="0 0 24 24">
              <Path d="M12 2 L20 21 L12 17 L4 21 Z" fill={c.accent} />
            </Svg>
            <Text style={styles.recenterText}>Re-centre</Text>
          </Pressable>
        ) : null}

        {/* Riding alone is almost always "nobody has joined yet" rather than a
            deliberate choice, so the fix is offered right where it is noticed
            instead of leaving an empty rider list to explain itself. */}
        {riders.length <= 1 && !navigating && !choosing ? (
          <Pressable
            onPress={() => void shareInvite()}
            accessibilityRole="button"
            accessibilityLabel="Share the ride code to invite riders"
            style={({ pressed }) => [styles.invite, pressed && styles.pressed]}
          >
            <View style={styles.inviteBody}>
              <Text style={styles.inviteTitle}>Nobody else has joined yet</Text>
              <Text style={styles.inviteSub}>
                Send the code {code} to your group
              </Text>
            </View>
            <Text style={styles.inviteAction}>Share</Text>
          </Pressable>
        ) : null}

        {voice.state !== "idle" || othersInCall > 0 || voice.error ? (
          <VoiceBar
            selfId={rider?.id ?? ""}
            members={voice.members}
            inCall={inCall}
            joining={voice.state === "joining"}
            muted={voice.muted}
            speaking={voice.speaking}
            linked={voice.linked}
            relayed={voice.relayed}
            error={voice.error}
            colorFor={colorForRider}
            onJoin={() => void voice.join()}
            onLeave={voice.leave}
            onToggleMute={voice.toggleMute}
          />
        ) : null}

        {suggestion ? (
          <GroupTripCard
            leaderName={suggestion.leader.name || "A rider"}
            leaderColor={colorForRider(suggestion.leader.id)}
            leaderIsHost={suggestion.leader.isHost}
            destinationLabel={suggestion.stops[suggestion.stops.length - 1].label}
            viaCount={suggestion.stops.length - 1}
            alsoGoing={suggestion.alsoGoing}
            distanceM={
              displayPosition
                ? distanceMeters(
                    displayPosition,
                    suggestion.stops[suggestion.stops.length - 1].lngLat,
                  )
                : null
            }
            switching={navigating}
            changed={suggestionChanged}
            collapsed={suggestionCollapsed}
            onAccept={acceptGroupTrip}
            onDismiss={() => setLaterTrip(suggestion.key)}
          />
        ) : null}

        {choosing ? (
          <RoutePreview
            routes={nav.routes}
            selectedIndex={nav.selectedIndex}
            stops={nav.stops}
            onSelect={nav.selectRoute}
            onAddStop={() => {
              setAddingStop(true);
              setSearchOpen(true);
            }}
            onRemoveStop={nav.removeStop}
            onStart={nav.begin}
            onCancel={nav.stop}
          />
        ) : navigating && nav.progress && nav.stops.length > 0 ? (
          <TripPanel
            remainingM={nav.progress.remainingM}
            remainingS={nav.progress.remainingS}
            destinationLabel={nav.stops[nav.stops.length - 1].label}
            voiceEnabled={nav.voiceEnabled}
            onToggleVoice={() => nav.setVoiceEnabled(!nav.voiceEnabled)}
            onStop={nav.stop}
          />
        ) : (
          <Pressable
            onPress={() => setSearchOpen(true)}
            accessibilityRole="button"
            accessibilityLabel="Choose a destination"
            style={({ pressed }) => [styles.searchBar, pressed && styles.pressed]}
          >
            <Text style={styles.searchGlyph}>◎</Text>
            <Text style={styles.searchText}>Where to?</Text>
            <Text style={styles.searchHint}>or hold the map</Text>
          </Pressable>
        )}

        <RiderSheet
          riders={riders}
          selfId={rider?.id ?? ""}
          selfPosition={displayPosition}
          colorFor={colorForRider}
          expanded={sheetExpanded}
          onExpandedChange={setSheetExpanded}
          onFocusRider={focusRider}
          onJoinTrip={joinTripOf}
          selfDestination={
            nav.stops.length > 0 ? nav.stops[nav.stops.length - 1].lngLat : null
          }
          now={now}
        />
      </View>

      <DestinationSearch
        visible={searchOpen}
        near={displayPosition}
        onClose={() => setSearchOpen(false)}
        onPick={(place) => pickDestination({ lngLat: place.lngLat, label: place.name })}
        riderOptions={riderOptions}
      />

      <ChatSheet
        visible={chatOpen}
        messages={chat.messages}
        selfId={rider?.id ?? ""}
        colorFor={colorForRider}
        onSend={chat.send}
        onClose={() => setChatOpen(false)}
      />
    </View>
  );
}

/**
 * A marker that slides to each new position instead of hopping.
 *
 * Its own component so the per-frame glide re-renders only this marker, not
 * the whole ride screen.
 */
function GlidingMarker({
  at,
  glideMs,
  children,
}: {
  at: LngLat;
  glideMs: number;
  children: ReactElement;
}) {
  const shown = useGlide(at, glideMs);
  if (!shown) return null;
  return (
    <Marker lngLat={shown} anchor="center">
      {children}
    </Marker>
  );
}

function ControlButton({
  label,
  onPress,
  active = false,
  small = false,
  badge = 0,
  accessibilityLabel,
  palette,
}: {
  label: string;
  onPress: () => void;
  active?: boolean;
  small?: boolean;
  /** Count shown in a corner dot, e.g. unread messages. Hidden at zero. */
  badge?: number;
  accessibilityLabel: string;
  palette: Palette;
}) {
  const styles = useMemo(() => makeStyles(palette), [palette]);

  return (
    <Pressable
      onPress={onPress}
      accessibilityRole="button"
      accessibilityLabel={accessibilityLabel}
      accessibilityState={{ selected: active }}
      style={({ pressed }) => [
        styles.control,
        active && styles.controlActive,
        pressed && styles.controlPressed,
      ]}
    >
      <Text
        style={[
          styles.controlText,
          small && styles.controlTextSmall,
          active && styles.controlTextActive,
        ]}
        numberOfLines={1}
      >
        {label}
      </Text>
      {badge > 0 ? (
        <View style={styles.badge} pointerEvents="none">
          <Text style={styles.badgeText}>{badge > 9 ? "9+" : badge}</Text>
        </View>
      ) : null}
    </Pressable>
  );
}

function Banner({
  text,
  actionLabel,
  onAction,
  bottomOffset,
  palette,
  warn = false,
}: {
  text: string;
  actionLabel?: string;
  onAction?: () => void;
  bottomOffset: number;
  palette: Palette;
  warn?: boolean;
}) {
  const styles = useMemo(() => makeStyles(palette), [palette]);

  return (
    <View
      style={[
        styles.banner,
        { bottom: bottomOffset + 170 },
        warn && { borderColor: palette.warning },
      ]}
    >
      <Text style={styles.bannerText}>{text}</Text>
      {actionLabel && onAction ? (
        <Pressable onPress={onAction} accessibilityRole="button" hitSlop={8}>
          <Text style={styles.bannerAction}>{actionLabel}</Text>
        </Pressable>
      ) : null}
    </View>
  );
}

const makeStyles = (c: Palette) =>
  StyleSheet.create({
    root: { flex: 1, backgroundColor: c.bg },

    header: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      paddingHorizontal: space.md,
    },
    headerCard: {
      flexDirection: "row",
      alignItems: "center",
      gap: space.md,
      backgroundColor: c.scrim,
      borderWidth: 1,
      borderColor: c.border,
      borderRadius: radius.lg,
      paddingVertical: space.md,
      paddingHorizontal: space.lg,
      elevation: 4,
      shadowColor: "#000",
      shadowOpacity: 0.18,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 3 },
    },
    headerMain: { flex: 1, gap: 3 },
    rideName: { color: c.text, fontSize: 17, fontWeight: "800" },
    statusLine: { flexDirection: "row", alignItems: "center", gap: space.sm },
    statusDot: { width: 8, height: 8, borderRadius: 4 },
    statusText: { color: c.textDim, fontSize: 12, fontWeight: "600" },
    codeChip: {
      color: c.accent,
      fontSize: 12,
      fontWeight: "800",
      letterSpacing: 2,
      fontFamily: font.mono,
    },
    leave: {
      paddingHorizontal: space.lg,
      paddingVertical: space.sm + 2,
      borderRadius: radius.md,
      borderWidth: 1,
      borderColor: c.danger,
    },
    leavePressed: { backgroundColor: "rgba(198, 40, 40, 0.15)" },
    leaveText: { color: c.danger, fontWeight: "800", fontSize: 13 },

    controls: { position: "absolute", right: space.md, gap: space.sm },
    control: {
      width: 46,
      height: 46,
      borderRadius: radius.md,
      backgroundColor: c.scrim,
      borderWidth: 1,
      borderColor: c.border,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: 2,
      elevation: 3,
      shadowColor: "#000",
      shadowOpacity: 0.15,
      shadowRadius: 5,
      shadowOffset: { width: 0, height: 2 },
    },
    controlActive: { borderColor: c.accent, backgroundColor: c.accentWash },
    badge: {
      position: "absolute",
      top: -6,
      right: -6,
      minWidth: 20,
      height: 20,
      borderRadius: 10,
      paddingHorizontal: 4,
      backgroundColor: c.accent,
      borderWidth: 2,
      borderColor: c.surface,
      alignItems: "center",
      justifyContent: "center",
    },
    badgeText: { color: c.onAccent, fontSize: 10, fontWeight: "900" },
    controlPressed: { opacity: 0.7 },

    sosButton: { borderColor: "#D32029", borderWidth: 2 },
    sosButtonActive: { backgroundColor: "#D32029" },
    sosButtonText: { color: "#D32029", fontSize: 13, fontWeight: "900" },
    sosButtonTextActive: { color: "#FFFFFF", fontSize: 18 },

    invite: {
      flexDirection: "row",
      alignItems: "center",
      gap: space.md,
      marginHorizontal: space.md,
      marginBottom: space.sm,
      backgroundColor: c.accentWash,
      borderWidth: 1,
      borderColor: c.accentDim,
      borderRadius: radius.md,
      paddingVertical: space.md,
      paddingHorizontal: space.lg,
    },
    inviteBody: { flex: 1, gap: 2 },
    inviteTitle: { color: c.text, fontSize: 14, fontWeight: "800" },
    inviteSub: { color: c.textDim, fontSize: 12 },
    inviteAction: { color: c.accent, fontSize: 14, fontWeight: "900" },
    controlText: { color: c.text, fontSize: 20, fontWeight: "700" },
    controlTextSmall: { fontSize: 10, fontWeight: "800", letterSpacing: 0.3 },
    controlTextActive: { color: c.accent },

    destPin: { alignItems: "center" },
    destPinHead: {
      width: 34,
      height: 34,
      borderRadius: 17,
      backgroundColor: "#EA4335",
      borderWidth: 3,
      borderColor: "#FFFFFF",
      alignItems: "center",
      justifyContent: "center",
      elevation: 6,
    },
    destPinHeadVia: { backgroundColor: "#FFFFFF", borderColor: "#1A73E8" },
    groupPinHead: { backgroundColor: "#FFFFFF" },
    groupPinGlyph: { fontSize: 16, fontWeight: "900" },
    groupPinLabel: {
      maxWidth: 160,
      color: "#0C1420",
      backgroundColor: "rgba(255,255,255,0.94)",
      fontSize: 11,
      fontWeight: "800",
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderRadius: 6,
      overflow: "hidden",
      marginBottom: 3,
    },
    destPinGlyph: { color: "#FFFFFF", fontSize: 15, fontWeight: "900" },
    destPinGlyphVia: { color: "#1A73E8" },
    destPinStem: {
      width: 3,
      height: 12,
      backgroundColor: "#FFFFFF",
      marginTop: -2,
      borderRadius: 2,
    },

    banner: {
      position: "absolute",
      left: space.md,
      right: space.md,
      flexDirection: "row",
      alignItems: "center",
      gap: space.md,
      backgroundColor: c.surfaceAlt,
      borderWidth: 1,
      borderColor: c.border,
      borderRadius: radius.md,
      paddingVertical: space.md,
      paddingHorizontal: space.lg,
      elevation: 3,
    },
    bannerText: { flex: 1, color: c.text, fontSize: 13, lineHeight: 18 },
    bannerAction: { color: c.accent, fontWeight: "800", fontSize: 13 },

    speedPill: {
      position: "absolute",
      left: space.md,
      width: 74,
      height: 74,
      borderRadius: 37,
      backgroundColor: c.scrim,
      borderWidth: 1,
      borderColor: c.border,
      alignItems: "center",
      justifyContent: "center",
      elevation: 3,
    },
    speedValue: { color: c.text, fontSize: 26, fontWeight: "900" },
    speedUnit: { color: c.textFaint, fontSize: 10, marginTop: -3 },

    bottom: {
      position: "absolute",
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: c.surface,
    },
    recenter: {
      position: "absolute",
      top: -58,
      right: space.md,
      flexDirection: "row",
      alignItems: "center",
      gap: space.sm,
      backgroundColor: c.surface,
      borderRadius: radius.pill,
      borderWidth: 1,
      borderColor: c.border,
      paddingVertical: space.md - 2,
      paddingHorizontal: space.lg,
      elevation: 6,
      shadowColor: "#000",
      shadowOpacity: 0.22,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 3 },
    },
    recenterText: { color: c.accent, fontSize: 15, fontWeight: "800" },
    searchBar: {
      flexDirection: "row",
      alignItems: "center",
      gap: space.md,
      marginHorizontal: space.md,
      marginBottom: space.sm,
      backgroundColor: c.surfaceAlt,
      borderWidth: 1,
      borderColor: c.border,
      borderRadius: radius.pill,
      paddingVertical: space.md,
      paddingHorizontal: space.lg,
    },
    pressed: { opacity: 0.75 },
    searchGlyph: { color: c.accent, fontSize: 16 },
    searchText: { flex: 1, color: c.text, fontSize: 15, fontWeight: "700" },
    searchHint: { color: c.textFaint, fontSize: 11 },

    errorRoot: {
      flex: 1,
      backgroundColor: c.bg,
      paddingHorizontal: space.xl,
      gap: space.md,
    },
    errorTitle: { color: c.text, fontSize: 24, fontWeight: "800" },
    errorBody: { color: c.textDim, fontSize: 15, lineHeight: 22 },
    errorButton: {
      marginTop: space.lg,
      backgroundColor: c.accent,
      borderRadius: radius.lg,
      paddingVertical: space.lg,
      alignItems: "center",
    },
    errorButtonText: { color: c.onAccent, fontWeight: "800", fontSize: 16 },
  });
